version: "3.7"

services:

  app-api:
    container_name: app-test-api
    tty: true
    image: webdevops/php-nginx:8.2
    environment:
      - APP_NAME=Laravel Teste
      - APP_URL=http://localhost
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=testDB
      - DB_USERNAME=user.test
      - DB_PASSWORD=password
      - WEB_DOCUMENT_ROOT=/var/www/public
      - APP_ENV=local
      - APP_DEBUG=true
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./application:/var/www
    working_dir: /var/www
    restart: on-failure
    networks:
      - homologacao

  db:
    container_name: app-test-db
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=testDB
      - MYSQL_USER=user.test
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306
    restart: on-failure
    networks:
      - homologacao

networks:
  homologacao:
    name: homologacao
    driver: bridge
