version: '3.8'

services:

  # Web Server Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./application:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app.dev
      - db
    networks:
      - setup_network

  db:
    container_name: app-test-db
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=testDB
      - MYSQL_USER=user.test
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306
    restart: on-failure
    networks:
      - setup_network

  # Application Service
  app.dev:
    container_name: app-test-api
    build: 
      context: ./docker/php
      dockerfile: Dockerfile
      args:
          user: benx
          uid: 1000
    volumes:
      - ./application:/var/www
    ports:
      - "9000:9000"
    working_dir: /var/www
    networks:
      - setup_network

networks:
  setup_network:
    driver: bridge